const QUESTIONS = {
  easy: [
    "Dogs or cats?",
    "What food could you not live without?",
    "What’s your favorite beer or drink?",
    "What’s your favorite hobby to do alone?",
    "What’s an ideal weekend for you?",
    "Where’s one place you’d like to travel next?",
    "What’s your favorite song right now?",
    "What’s your favorite movie or comfort movie?",
    "What’s your favorite place in the world to go?",
    "What’s the last book you read?",
    "What sport did you fall in love with?",
    "What’s your biggest pet peeve?",
    "Are you more of an introvert or extrovert?",
    "Do you usually stay friends with exes?",
    "Are you confrontational or avoid conflict?",
    "What’s something you can’t go a day without doing?",
    "What fictional character do you relate to most?",
    "What song makes you unconditionally happy?",
    "What’s the weirdest thing about you?",
    "What’s your favorite hobby to do with someone else?"
  ],
  medium: [
    "What do you value most in a person?",
    "What qualities do you admire in your parents?",
    "What would your best friend say is your best quality?",
    "What trait do you envy in others?",
    "Are you more into looks or brains?",
    "What’s a relationship deal breaker for you?",
    "How do you feel about sharing passwords in a relationship?",
    "Would you ever relocate for love?",
    "What’s your love language?",
    "Do you believe in second chances?",
    "How do you handle being in a bad mood—alone or with support?",
    "What’s the most spontaneous thing you’ve done recently?",
    "How important is personal space in a relationship?",
    "Do you believe honesty means sharing everything?",
    "What role does humor play in your relationships?",
    "What’s the most adventurous thing you’ve done?",
    "How do you usually express frustration?",
    "What does compatibility mean to you?",
    "How important is physical fitness to you and a partner?",
    "How do you usually handle jealousy?"
  ],
  hard: [
    "What’s your philosophy in life?",
    "What makes you feel accomplished?",
    "What are you most thankful for?",
    "What accomplishment are you most proud of?",
    "What did your past relationships teach you?",
    "Why did your last relationship end?",
    "Have you ever been in love? What did it feel like?",
    "What’s the craziest thing you’ve ever done for love?",
    "What’s your biggest fear in relationships?",
    "What’s the hardest lesson you’ve learned about love?",
    "When have you felt the most alive?",
    "What’s the biggest mistake you’ve made and what did you learn?",
    "How do you respond to emotional stress?",
    "What makes you feel emotionally safe?",
    "What makes you feel anxious or uneasy?",
    "How do you handle constructive criticism from a partner?",
    "What’s something people often misunderstand about you?",
    "What’s your biggest regret so far?",
    "What’s one dream you still want to accomplish?",
    "What’s the greatest struggle you’ve overcome?"
  ],
  veryHard: [
    "Who are you, really, beneath roles and labels?",
    "What do you think about when you’re alone?",
    "What is your deepest fear?",
    "When have you felt the lowest in your life?",
    "What part of yourself are you still working on?",
    "What do you struggle to give in relationships?",
    "How do you handle conflict when emotions run high?",
    "What does love mean to you now vs earlier in life?",
    "What does a healthy long-term partnership look like to you?",
    "What would your future partner need to understand about you?",
    "What are you afraid a partner might leave you for?",
    "How do you want to grow emotionally with someone?",
    "What would you want to change about yourself for the better?",
    "How do you wish to be remembered by the people you love?",
    "How would you summarize your life purpose?"
  ]
};

export default QUESTIONS;
